namespace Welco.Shared.Common.DTOs.Content
{
    public class DocumentDto { public Guid Id { get; set; } public string Title { get; set; } = string.Empty; public string DocType { get; set; } = string.Empty; public string FileUrl { get; set; } = string.Empty; public int FileSizeKB { get; set; } public Guid? ProductId { get; set; } public DateTime PublishedDate { get; set; } public DateTime CreatedAt { get; set; } }
    public class LandingPageDto { public Guid Id { get; set; } public string Type { get; set; } = string.Empty; public string Slug { get; set; } = string.Empty; public string HeroTitle { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } }
    public class HelpCategoryDto { public Guid Id { get; set; } public string Name { get; set; } = string.Empty; public string? Icon { get; set; } public int ArticleCount { get; set; } public DateTime CreatedAt { get; set; } }
    public class HelpArticleDto { public Guid Id { get; set; } public Guid CategoryId { get; set; } public string CategoryName { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Body { get; set; } = string.Empty; public string Slug { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } }
    public class FAQItemDto { public Guid Id { get; set; } public string Question { get; set; } = string.Empty; public string Answer { get; set; } = string.Empty; public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } }
    public class SupportTicketDto { public Guid Id { get; set; } public Guid UserId { get; set; } public string Subject { get; set; } = string.Empty; public string Message { get; set; } = string.Empty; public string Status { get; set; } = string.Empty; public string? Reply { get; set; } public DateTime CreatedAt { get; set; } public DateTime? RepliedAt { get; set; } }
    public class TradeShowEventDto { public Guid Id { get; set; } public string Name { get; set; } = string.Empty; public string Location { get; set; } = string.Empty; public DateTime StartDate { get; set; } public DateTime EndDate { get; set; } public DateTime CreatedAt { get; set; } }
}
